# Generated by Django 4.0.6 on 2022-07-21 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_start_point', models.TextField()),
                ('address_end_point', models.TextField()),
                ('transportation', models.CharField(choices=[('metro', 'Metro'), ('auto', 'Auto'), ('camioneta', 'Camioneta'), ('motocicleta', 'Motocicleta'), ('bus-transantiago', 'Bus Transantiago'), ('bus', 'Bus'), ('avion-nacional', 'Avión (Nacional)'), ('avion-internacional', 'Avión (Internacional)'), ('caminando', 'Caminando')], max_length=100)),
                ('kilometers', models.IntegerField()),
                ('round_trip', models.CharField(choices=[('ida', 'Ida'), ('vuelta', 'Vuelta'), ('ida-vuelta', 'Ida y Vuelta')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='Participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
